name: ROS 2 CI

on:
  push:
  pull_request:

jobs:
  test:
    name: ROS 2 ${{ matrix.ros_distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [humble, jazzy, kilted, lyrical]
    container:
      image: ros:${{ matrix.ros_distro }}-ros-base
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        shell: bash
        run: |
          apt-get update
          rosdep update
          rosdep install --from-paths . --ignore-src -r -y \
            --rosdistro "${{ matrix.ros_distro }}"
      - name: Build
        shell: bash
        run: |
          source "/opt/ros/${{ matrix.ros_distro }}/setup.bash"
          colcon build --packages-select rtamt4ros2 --event-handlers console_direct+
      - name: Test
        shell: bash
        run: |
          source "/opt/ros/${{ matrix.ros_distro }}/setup.bash"
          source install/setup.bash
          colcon test --packages-select rtamt4ros2 --event-handlers console_direct+
          colcon test-result --verbose
